security:
    enable_authenticator_manager: true  # indispensable depuis Symfony 6

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur   # ton entité Utilisateur
                property: email                 # identification par email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Active la connexion via formulaire classique
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home

            logout:
                path: app_logout                # route à définir dans ton controller
                target: app_home                # redirection après déconnexion

            # Tu pourras plus tard activer des options ici :
            # remember_me:
            #     secret: '%kernel.secret%'
            #     lifetime: 604800 # 7 jours

    access_control:
        # exemple : restreindre /admin aux admins
        - { path: ^/admin, roles: ROLE_ADMIN }
        # tu pourras protéger d'autres pages plus tard, ex:
        # - { path: ^/profil, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
