GET https://127.0.0.1:8000/api
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjUyNzMwNjQsImV4cCI6MTc2NTI3NjY2NCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJlbWFpbCI6ImFkbWluQGNyYWZ0eUNyb2NoZXQuZnIifQ.LeIpPybjHTKobaqpwtE3jE6b_PK8UlzfLGtkrLu9t49vXnImAxsAlH-2WJM8mkTrnvqahA1J7rltlLcIzIBwax1KEzsQytVe26Sid0Jelz4IFaFm_PM_HP_x4D6WLSPZcQamGXeCuDBqN8viNDhDckhhj19c3mvgyy1mnVYu2Hwpru6w89gWL5R1IgRHtQypuvyUDuZiPMN5JCaBPZV2as6QrWsro26p5DU7Bhsz394jfAdL1x-eMzBpb4cEPw3jH5_nPnoF5Cg4nCS7sZDzR9W52n4hIRsIj-7FoLFOLDKXbBMzPYulUjEZMp3dJSmZ4aI05wopkyn2wu6PIJgQ3g
###

GET https://127.0.0.1:8000/api/categories

###

curl -i -X POST http://127.0.0.1:8000/api/login_check \
  -H "Content-Type: application/json" \
  -d '{"email":"tot@test.com","password":"123456"}'

###

POST https://127.0.0.1:8000/api/login_check
Content-Type: application/json

{
  "username": "admin@craftyCrochet.fr",
  "password": "123456"
}
